export { Home } from "./Home/Home"
export { CollectionPage } from "./CollectionPage/CollectionPage"
export { ItemDetail } from "./ItemDetail/ItemDetail"
export { Cart } from "./Cart/Cart"
export { PiecePage } from "./PiecePage/PiecePage"
export { SearchItem } from "./Search/SearchItem" 
export { NotFound } from "./Search/components/NotFound"